### ISSUE TITLE
Error: ENOENT: no such file or directory, uv_cwd

### ISSUE THREAD

**Issue by louisgv** [exogen/postinstall-build#16]
I tried to run this with babel and some other dependencies but seems like it failed :(...

./scripts/postinstall simply do `console.log(process.cwd())`

devDependencies:
```
"babel-cli": "^6.24.1",
    "babel-eslint": "^7.2.2",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-stage-0": "^6.24.1",
    "babel-runtime": "^6.23.0",
    "chokidar-cli": "^1.2.0",
    "cross-env": "^4.0.0",
    "eslint": "^3.19.0",
    "eslint-config-semistandard": "^8.0.0",
    "eslint-config-standard": "^10.2.0",
    "eslint-plugin-import": "~2.2.0",
    "eslint-plugin-node": "~4.2.2",
    "eslint-plugin-promise": "~3.5.0",
    "eslint-plugin-standard": "~3.0.1",
    "husky": "^0.13.3",
    "istanbul": "^0.4.5",
    "lint-staged": "^3.4.0",
    "mocha": "^3.2.0",
    "npm-run-all": "^4.0.2",
    "nsp": "^2.6.3",
    "testdouble": "^2.1.2"
```

Node and npm version:
```
Now using node v6.5.0 (npm v3.10.3)
```

Error Log:
```
shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
path.js:1144
          cwd = process.cwd();
                        ^

Error: ENOENT: no such file or directory, uv_cwd
    at Error (native)
    at Object.resolve (path.js:1144:25)
    at startup (bootstrap_node.js:127:32)
    at bootstrap_node.js:509:3
{ Error: Command failed: sh -c node ./scripts/postinstall

    at ChildProcess.<anonymous> (/usr/local/opt/nvm/versions/node/v6.5.0/lib/node_modules/@cet/create-cet-widget/node_modules/postinstall-build/index.js:53:13)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: 'sh -c node ./scripts/postinstall' }
```

**Comment by exogen** [comment]
That's a strange error, seems like it would be coming from a low level in Node. Can you post your `scripts` section as well?

**Comment by louisgv** [comment]
Here goes:
```
 "scripts": {
    "postinstall": "postinstall-build lib",
    "build": "babel -d lib src"
}
```
