### ISSUE TITLE
It fails right after build with npm@5.3.0

### ISSUE THREAD

**Issue by awesomejerry** [exogen/postinstall-build#29]
Not sure if it helps. Here's the log:

```
1601 verbose stack Error: May not delete: /Users/user/Workspace/organization/core/test/node_modules/@cool/node_modules/.bin
1601 verbose stack     at gentlyRm (/Users/user/.nvm/versions/node/v8.1.4/lib/node_modules/npm/lib/utils/gently-rm.js:49:15)
1601 verbose stack     at gentlyRmBinRoot (/Users/user/.nvm/versions/node/v8.1.4/lib/node_modules/npm/lib/unbuild.js:86:12)
1601 verbose stack     at cb (/Users/user/.nvm/versions/node/v8.1.4/lib/node_modules/npm/node_modules/slide/lib/async-map.js:47:24)
1601 verbose stack     at next (/Users/user/.nvm/versions/node/v8.1.4/lib/node_modules/npm/node_modules/fs-vacuum/vacuum.js:66:14)
1601 verbose stack     at /Users/user/.nvm/versions/node/v8.1.4/lib/node_modules/npm/node_modules/fs-vacuum/vacuum.js:54:9
1601 verbose stack     at FSReqWrap.oncomplete (fs.js:135:15)
1602 verbose cwd /Users/user/Workspace/organization/core/test/node_modules/@cool
1603 verbose Darwin 16.7.0
1604 verbose argv "/Users/user/.nvm/versions/node/v8.1.4/bin/node" "/Users/jerrythebest/.nvm/versions/node/v8.1.4/bin/npm" "prune" "--production"
1605 verbose node v8.1.4
1606 verbose npm  v5.3.0
1607 error May not delete: /Users/user/Workspace/organization/core/test/node_modules/@cool/node_modules/.bin
1608 verbose exit [ 1, true ]
```

Btw, it works great with node@6.11.2 (npm@3.10.10)!

**Comment by zglueck** [comment]
I was seeing the same `May not delete` failure with 5.3.0, upgrading to 5.4.1 resolved the issue.

**Comment by exogen** [comment]
Great to know that 5.4.1 is a solution, I haven't had time to look into this yet. I'd like to support as many npm versions as possible so it's still on my to-do  list!
